name: "ReadTheDocs Trigger"
description: "Trigger a build on ReadTheDocs"
inputs:
  webhook_url:
    description: "The webhook URL from ReadTheDocs. This will have the form: https://readthedocs.org/api/v2/webhook/{webhook_id}/"
    required: true
  webhook_token:
    description: "The webhook token from ReadTheDocs"
    required: true
  commit_ref:
    description: "The reference for the current commit"
    required: true
runs:
  using: "node16"
  main: "compiled/index.js"
